version: '2'
services:
        nginx:
             build: ./nginx/
             container_name: nginx
             volumes:
                  - ./nginx/www/:/var/www/nginx
             ports:
                  - "8080:80"
             networks:
                  - se_backend
networks:
     se_backend:
        driver: bridge
